spring:
  application:
    name: mysite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysite?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Sh20060401
  servlet:
    session:
      timeout: 30ms
  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Sh20060401

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.somehow.mysite

knife4j:
  enable: true
  setting:
    language: zh_cn

artalk:
  server: http://localhost:23366
  site: MySite博客
  enabled: true